# Generated by Django 4.2.30 on 2026-04-20 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymongo_refund_id', models.CharField(blank=True, max_length=200)),
                ('amount', models.BigIntegerField(help_text='Amount in centavos')),
                ('reason', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='PayMongoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('payment_method_id', models.CharField(blank=True, max_length=200)),
                ('payment_id', models.CharField(blank=True, max_length=200)),
                ('amount', models.BigIntegerField(help_text='Amount in centavos')),
                ('currency', models.CharField(default='PHP', max_length=3)),
                ('status', models.CharField(choices=[('awaiting_payment_method', 'Awaiting Payment Method'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='awaiting_payment_method', max_length=30)),
                ('paymongo_event_type', models.CharField(blank=True, max_length=100)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paymongo_transaction', to='orders.order')),
            ],
        ),
    ]
