# Generated by Django 5.2.16 on 2026-10-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_webhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymongotransaction',
            name='payment_method_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
