# Generated by Django 5.2.16 on 2026-10-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transaction_method_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymongotransaction',
            name='payment_intent_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='refund',
            name='paymongo_refund_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
