# Generated by Django 4.2.30 on 2026-05-06 09:36

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_riderprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderprofile',
            name='drivers_license_back',
            field=models.FileField(blank=True, null=True, upload_to='rider_docs/', validators=[utils.validators.validate_document_upload]),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='drivers_license_front',
            field=models.FileField(blank=True, null=True, upload_to='rider_docs/', validators=[utils.validators.validate_document_upload]),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='government_id_back',
            field=models.FileField(blank=True, null=True, upload_to='rider_docs/', validators=[utils.validators.validate_document_upload]),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='government_id_front',
            field=models.FileField(blank=True, null=True, upload_to='rider_docs/', validators=[utils.validators.validate_document_upload]),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='selfie_with_id',
            field=models.FileField(blank=True, null=True, upload_to='rider_docs/', validators=[utils.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='vehicle_cr',
            field=models.FileField(blank=True, null=True, upload_to='rider_docs/', validators=[utils.validators.validate_document_upload]),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='vehicle_or',
            field=models.FileField(blank=True, null=True, upload_to='rider_docs/', validators=[utils.validators.validate_document_upload]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[utils.validators.validate_image_upload]),
        ),
    ]
