# Generated by Django 5.2.16 on 2026-09-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
