# Generated by Django 4.2.30 on 2026-05-06 09:36

from decimal import Decimal, InvalidOperation

from django.db import migrations, models
import utils.validators


META_PREFIXES = {
    'tagline': 'Tagline: ',
    'minimum_load_kg': 'Minimum load: ',
    'turnaround': 'Turnaround: ',
    'payments': 'Payments: ',
    'unclaimed_policy': 'Policy: ',
    'customer_notes': 'Customer notes: ',
}


def migrate_shop_metadata(apps, schema_editor):
    Shop = apps.get_model('shops', 'Shop')
    for shop in Shop.objects.all():
        description_lines = []
        updates = {}
        for line in (shop.description or '').splitlines():
            matched = False
            for field, prefix in META_PREFIXES.items():
                if line.startswith(prefix):
                    value = line[len(prefix):].strip()
                    if field == 'minimum_load_kg':
                        value = value.removesuffix(' kg').strip()
                        try:
                            updates[field] = Decimal(value) if value else None
                        except (InvalidOperation, TypeError, ValueError):
                            updates[field] = None
                    elif field == 'payments':
                        updates[field] = [item.strip() for item in value.split(',') if item.strip()]
                    else:
                        updates[field] = value
                    matched = True
                    break
            if not matched:
                description_lines.append(line)
        for field, value in updates.items():
            setattr(shop, field, value)
        shop.description = '\n'.join(description_lines).strip()
        shop.save(update_fields=['description', *updates.keys()])


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='customer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='minimum_load_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='payments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='shop',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='shop',
            name='turnaround',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shop',
            name='unclaimed_policy',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RunPython(migrate_shop_metadata, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_logos/', validators=[utils.validators.validate_image_upload]),
        ),
        migrations.AddConstraint(
            model_name='deliveryslot',
            constraint=models.UniqueConstraint(fields=('shop', 'date', 'time_start', 'time_end'), name='unique_delivery_slot_per_shop'),
        ),
        migrations.AddConstraint(
            model_name='deliveryslot',
            constraint=models.CheckConstraint(check=models.Q(('max_capacity__gte', 1)), name='delivery_slot_positive_capacity'),
        ),
        migrations.AddConstraint(
            model_name='deliveryslot',
            constraint=models.CheckConstraint(check=models.Q(('current_bookings__gte', 0)), name='delivery_slot_non_negative_bookings'),
        ),
        migrations.AddConstraint(
            model_name='deliveryslot',
            constraint=models.CheckConstraint(check=models.Q(('time_end__gt', models.F('time_start'))), name='delivery_slot_valid_time_range'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('shop', 'name'), name='unique_service_per_shop'),
        ),
    ]
