# Generated by Django 4.2.30 on 2026-05-09 15:13

from django.db import migrations, models
import shops.models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_customer_notes_shop_minimum_load_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=shops.models._shop_logo_upload, validators=[utils.validators.validate_image_upload]),
        ),
    ]
