# Generated by Django 4.2.30 on 2026-05-15 13:40

from django.db import migrations, models
import shops.models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_add_suspended_shop_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=shops.models._shop_banner_upload, validators=[utils.validators.validate_image_upload]),
        ),
    ]
