# Generated by Django 5.2.16 on 2026-09-29 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_add_shop_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_per_piece',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
