# Generated by Django 5.2.16 on 2026-09-29 22:15

import shops.models
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_alter_service_price_per_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='owner_government_id',
            field=models.FileField(blank=True, null=True, upload_to=shops.models._shop_owner_doc_upload, validators=[utils.validators.validate_document_upload]),
        ),
        migrations.AddField(
            model_name='shop',
            name='owner_selfie_with_id',
            field=models.ImageField(blank=True, null=True, upload_to=shops.models._shop_owner_doc_upload, validators=[utils.validators.validate_image_upload]),
        ),
    ]
