# Generated by Django 4.2.30 on 2026-05-06 09:36

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoproof',
            name='photo',
            field=models.ImageField(upload_to='proof_photos/', validators=[utils.validators.validate_image_upload]),
        ),
        migrations.AddConstraint(
            model_name='orderservice',
            constraint=models.UniqueConstraint(fields=('order', 'service'), name='unique_order_service'),
        ),
        migrations.AddConstraint(
            model_name='orderservice',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='order_service_non_negative_quantity'),
        ),
        migrations.AddConstraint(
            model_name='orderservice',
            constraint=models.CheckConstraint(check=models.Q(('weight_kg__isnull', True), ('weight_kg__gte', 0), _connector='OR'), name='order_service_non_negative_weight'),
        ),
        migrations.AddConstraint(
            model_name='orderservice',
            constraint=models.CheckConstraint(check=models.Q(('subtotal__gte', 0)), name='order_service_non_negative_subtotal'),
        ),
    ]
