# Generated by Codex on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_photoproof_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoproof',
            name='proof_type',
            field=models.CharField(
                choices=[
                    ('pickup', 'Pickup'),
                    ('dropoff', 'Shop Drop-Off'),
                    ('delivery', 'Delivery'),
                ],
                max_length=20,
            ),
        ),
    ]
