# Generated by Django 4.2.30 on 2026-05-09 15:13

from django.db import migrations, models
import orders.models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderstatuslog_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoproof',
            name='photo',
            field=models.ImageField(upload_to=orders.models._proof_photo_upload, validators=[utils.validators.validate_image_upload]),
        ),
    ]
