# Generated by Django 5.2.16 on 2026-09-29 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_photoproof_photo'),
        ('shops', '0006_alter_service_price_per_kg_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shops.service'),
        ),
        migrations.AlterField(
            model_name='photoproof',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
