# Generated by Django 5.2.16 on 2026-09-30 05:11

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import F


def backfill_subtotals(apps, schema_editor):
    # Orders placed before promos existed had no discount: subtotal == total.
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(subtotal_amount__isnull=True).update(subtotal_amount=F('total_amount'))


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderservice_service_and_more'),
        ('shops', '0008_promotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shops.promotion'),
        ),
        migrations.AddField(
            model_name='order',
            name='promotion_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RunPython(backfill_subtotals, migrations.RunPython.noop),
    ]
