# Generated by Django 5.2.16 on 2026-10-01 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_promotion_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_confirmed_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='weigh_at_shop',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='photoproof',
            name='proof_type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('dropoff', 'Shop Drop-Off'), ('delivery', 'Delivery'), ('weight', 'Scale Reading')], max_length=20),
        ),
    ]
