# Generated by Django 5.2.16 on 2026-10-01 04:58

from datetime import timedelta

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_due_dates(apps, schema_editor):
    # Open, unpaid online orders get a fresh deadline from now (fair warning, no instant COD switch).
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(
        payment_due_at__isnull=True,
        payment_status__in=['unpaid', 'failed'],
    ).exclude(payment_method='cod').exclude(
        status__in=['delivered', 'cancelled', 'declined'],
    ).exclude(weigh_at_shop=True, price_confirmed_at__isnull=True).update(
        payment_due_at=timezone.now() + timedelta(hours=settings.PAYMENT_DUE_HOURS),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_weigh_at_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reminders_sent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(backfill_due_dates, migrations.RunPython.noop),
    ]
