# Generated by Django 5.2.16 on 2026-10-02 02:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_payment_deadline'),
        ('shops', '0008_promotions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='order_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shop', '-created_at'], name='order_shop_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['paymongo_payment_intent_id'], name='order_pi_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('payment_due_at__isnull', False)), fields=['payment_due_at'], name='order_due_idx'),
        ),
    ]
